name: Build bitcoind

on: [push]

#on:
#  push:
#    tags:
#      - '*'

jobs:
  build:
    name: Build Bitcoind
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        arch:
          - arm32v7
          - arm64
          - amd64

        subver:
          - '0.16'
#          - '0.17'
          - '0.18'

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Register self-compiled qemu
        if: matrix.arch != 'amd64'
        run: docker run --rm --privileged meedamian/simple-qemu:v4.1.0-${{matrix.arch}} -p yes

        # This step is only run when `qemu` emulation is necessary.  `sed` command here prepares `Dockerfile` so that
        #   emulated architecture is always used instead of host's native one.
        # First `-e` (aka `--expression`) matches two consecutive words "FROM alpine", captures them as `\1`, and `\2`
        #   respectively, and inserts "${{matrix.arch}}/" between them. Note that `(`, `)`, `/` must be escaped.
        # Second `-e` matches BDB version, and appends "-${{matrix.arch}}" to it.
        #   Note that `&` represents match.
      - name: Change Dockerfile to use arch-specific base images
        if: matrix.arch != 'amd64'
        run: |
          CPU=${{matrix.arch}}
          if [[ "${CPU}" == "arm64" ]]; then
            CPU="arm64v8"
          fi

          sed -i ${{matrix.subver}}/Dockerfile \
            -e "s|^FROM alpine|FROM $CPU/alpine|g" \
            -e "s|db-4.8.30.NC|&-${{matrix.arch}}|g"

      - name: Build Docker image
        if: matrix.arch == 'amd64'
        run: DOCKER_BUILDKIT=1 docker build --build-arg "variant=checked" ${{matrix.subver}}/

      - name: Build Docker image (quick)
        if: matrix.arch != 'amd64'
        run: DOCKER_BUILDKIT=1 docker build ${{matrix.subver}}/

