name: Build bitcoind

on:
  push:
    branches:
      - master

#on:
#  push:
#    tags:
#      - '*'

jobs:
  build:
    name: Build Bitcoind
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm32v7
          - arm64
          - amd64

        subver:
          - '0.16'
#          - '0.17'
          - '0.18'
        qemu:
          - v3.1.1
          - v4.1.0

    steps:
      - uses: actions/checkout@v1.0.0

      # NOTE: qemu v3.1.1 used instead of currently newest v4.1.0, because v4 is **much** slower for aarch64, see:
      #   https://github.com/meeDamian/docker-berkeleydb/runs/232390723
      - name: Register self-compiled qemu
        if: matrix.arch != 'amd64'
        run: docker run --rm --privileged meedamian/simple-qemu:${{matrix.qemu}}-${{matrix.arch}} -p yes

        # This step is only run when `qemu` emulation is necessary.  `sed` command here prepares `Dockerfile` so that
        #   emulated architecture is always used instead of host's native one.
        # First `-e` (aka `--expression`) matches all occurrences of two consecutive words "FROM alpine", and
        #   replaces them with  "FROM $CPU/alpine", where $CPU is ${{matrix.arch}}, converted to Alpine tags format.
        # Second `-e` matches BDB version, and appends "-${{matrix.arch}}" to it.
        #   Note that `&` represents match.
      - name: Change Dockerfile to use arch-specific base images
        if: matrix.arch != 'amd64'
        run: |
          CPU=${{matrix.arch}}
          if [[ "${CPU}" == "arm64" ]]; then
            CPU="arm64v8"
          fi

          sed -i ${{matrix.subver}}/Dockerfile \
            -e "s|^FROM alpine|FROM $CPU/alpine|g" \
            -e "s|db-4.8.30.NC|&-${{matrix.arch}}|g"

      - name: Build Docker image (quick)
        run: DOCKER_BUILDKIT=1 docker build ${{matrix.subver}}/

