name: Build bitcoind

on: [push]

#on:
#  push:
#    tags:
#      - '*'

jobs:
  build:
    name: Build Bitcoind
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        arch:
          - arm32v7
          - arm64v8
          - amd64

    steps:
      - uses: actions/checkout@v1.0.0

#      - name: Register self-compiled qemu
#        if: matrix.arch != 'amd64'
#        run: docker run --rm --privileged meedamian/simple-qemu:v4.1.0-${{matrix.arch}} -p yes

      - name: Register self-compiled qemu
        if: matrix.arch == 'arm32v7'
        run: docker run --rm --privileged meedamian/simple-qemu:v4.1.0-arm -p yes

      - name: Register self-compiled qemu
        if: matrix.arch == 'arm64v8'
        run: docker run --rm --privileged meedamian/simple-qemu:v4.1.0-aarch64 -p yes

      # TODO: check if the line importing berkeleydb needs editing too
      - name: Change Dockerfile to use arch-specific base images
        if: matrix.arch != 'amd64'
        run: sed -ie "s/FROM alpine/FROM ${{ matrix.arch }}\/alpine/g" 0.16/Dockerfile

      - name: Build Docker image
        run: >
          DOCKER_BUILDKIT=1 docker build 0.16/
            --file      0.16/Dockerfile
            --platform  linux/${{ matrix.arch }}

