name: Build bitcoind

on: [push]

#on:
#  push:
#    tags:
#      - '*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
#          - arm
#          - aarch64
          - amd64
        bench:
          - true
          - false

    steps:
      - uses: actions/checkout@master

      - name: Register self-compiled qemu
        if: matrix.arch != 'amd64' && matrix.bench == true
        run: docker run --rm --privileged meedamian/simple-qemu:v4.1.0-${{matrix.arch}} -p yes

      - name: Change Dockerfile to use arch-specific base images
        if: matrix.arch != 'amd64' && matrix.bench == true
        run: |
          if [[ "${{ matrix.arch }}" == "aarch64" ]]; then
            sed -ie 's/FROM alpine/FROM arm64v8\/alpine/g' 0.16/Dockerfile
            exit 0
          fi

          if [[ "${{ matrix.arch }}" == "arm" ]]; then
            sed -ie 's/FROM alpine/FROM arm32v6\/alpine/g' 0.16/Dockerfile
            exit 0
          fi

      - name: Build Docker image
        if: matrix.arch == 'amd64' || matrix.bench == true
        run: |
          if [[ "${{ matrix.bench }}" == "true" ]]; then
            sed -i '/--disable-bench/d' 0.16/Dockerfile
          fi

          docker build  0.16/  -f 0.16/Dockerfile

